MLIR: lib/Analysis/AffineAnalysis.cpp File Reference
AffineAnalysis.cpp File Reference
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "affine-analysis"
Functions
static Value getSupportedReduction (AffineForOp forOp, unsigned pos, AtomicRMWKind &kind)
Get the value that is being reduced by pos-th reduction in the loop if such a reduction can be performed by affine parallel loops.
static LogicalResult getOpIndexSet (Operation *op, FlatAffineValueConstraints *indexSet)
Computes the iteration domain for 'op' and populates 'indexSet', which encapsulates the constraints involving loops surrounding 'op' and potentially involving any Function symbols.
static void buildDimAndSymbolPositionMaps (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, ValuePositionMap *valuePosMap, FlatAffineValueConstraints *dependenceConstraints)
static void initDependenceConstraints (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, const ValuePositionMap &valuePosMap, FlatAffineValueConstraints *dependenceConstraints)
static void addDomainConstraints (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, const ValuePositionMap &valuePosMap, FlatAffineValueConstraints *dependenceDomain)
static LogicalResult addMemRefAccessConstraints (const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, const ValuePositionMap &valuePosMap, FlatAffineValueConstraints *dependenceDomain)
static unsigned getNumCommonLoops (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, SmallVectorImpl< AffineForOp > *commonLoops=nullptr)
static Block * getCommonBlock (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, const FlatAffineValueConstraints &srcDomain, unsigned numCommonLoops)
Returns Block common to 'srcAccess.opInst' and 'dstAccess.opInst'.
static bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, const FlatAffineValueConstraints &srcDomain, unsigned numCommonLoops)
static void addOrderingConstraints (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, unsigned loopDepth, FlatAffineValueConstraints *dependenceDomain)
static void computeDirectionVector (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, unsigned loopDepth, FlatAffineValueConstraints *dependenceDomain, SmallVector< DependenceComponent, 2 > *dependenceComponents)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-analysis"
Definition at line 30 of file AffineAnalysis.cpp.
Function Documentation
addDomainConstraints()
static void addDomainConstraints (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, const ValuePositionMap & valuePosMap, FlatAffineValueConstraints * dependenceDomain) static
Definition at line 492 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::FlatAffineValueConstraints::getValue(), and map().
Referenced by mlir::checkMemrefAccessDependence().
addMemRefAccessConstraints()
static LogicalResult addMemRefAccessConstraints (const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, const ValuePositionMap & valuePosMap, FlatAffineValueConstraints * dependenceDomain) static
Definition at line 569 of file AffineAnalysis.cpp.
References mlir::FlatAffineValueConstraints::addBound(), mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::appendLocalId(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::EQ, mlir::failed(), mlir::failure(), mlir::AffineValueMap::getAffineMap(), mlir::getFlattenedAffineExprs(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::AffineMap::getNumDims(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::FlatAffineConstraints::getNumSymbolIds(), mlir::AffineMap::getNumSymbols(), mlir::AffineValueMap::getOperands(), mlir::isForInductionVar(), mlir::isValidSymbol(), and mlir::success().
Referenced by mlir::checkMemrefAccessDependence().
addOrderingConstraints()
static void addOrderingConstraints (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, unsigned loopDepth, FlatAffineValueConstraints * dependenceDomain) static
Definition at line 798 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::getNumCols(), getNumCommonLoops(), mlir::FlatAffineConstraints::getNumDimIds(), and min().
Referenced by mlir::checkMemrefAccessDependence().
buildDimAndSymbolPositionMaps()
static void buildDimAndSymbolPositionMaps (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, ValuePositionMap * valuePosMap, FlatAffineValueConstraints * dependenceConstraints) static
Definition at line 333 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::AffineValueMap::getOperands(), mlir::FlatAffineValueConstraints::getValues(), mlir::isForInductionVar(), mlir::isValidSymbol(), and value.
Referenced by mlir::checkMemrefAccessDependence().
computeDirectionVector()
static void computeDirectionVector (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, unsigned loopDepth, FlatAffineValueConstraints * dependenceDomain, SmallVector< DependenceComponent, 2 > * dependenceComponents) static
Definition at line 824 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::getConstantBound(), mlir::FlatAffineConstraints::getNumCols(), getNumCommonLoops(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineValueConstraints::insertDimId(), mlir::FlatAffineConstraints::LB, max(), min(), mlir::FlatAffineValueConstraints::projectOut(), and mlir::FlatAffineConstraints::UB.
Referenced by mlir::checkMemrefAccessDependence().
getCommonBlock()
static Block* getCommonBlock (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, const FlatAffineValueConstraints & srcDomain, unsigned numCommonLoops) static
Returns Block common to 'srcAccess.opInst' and 'dstAccess.opInst'.
Definition at line 722 of file AffineAnalysis.cpp.
References mlir::Operation::getBlock(), mlir::getForInductionVarOwner(), mlir::Block::getParentOp(), mlir::FlatAffineValueConstraints::getValue(), mlir::Operation::hasTrait(), mlir::MemRefAccess::opInst, and mlir::Block::push_back().
Referenced by srcAppearsBeforeDstInAncestralBlock().
getNumCommonLoops()
static unsigned getNumCommonLoops (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, SmallVectorImpl< AffineForOp > * commonLoops = nullptr) static
Definition at line 700 of file AffineAnalysis.cpp.
References mlir::getForInductionVarOwner(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineValueConstraints::getValue(), mlir::isForInductionVar(), and min().
Referenced by addOrderingConstraints(), mlir::checkMemrefAccessDependence(), and computeDirectionVector().
getOpIndexSet()
static LogicalResult getOpIndexSet (Operation * op, FlatAffineValueConstraints * indexSet) static
Computes the iteration domain for 'op' and populates 'indexSet', which encapsulates the constraints involving loops surrounding 'op' and potentially involving any Function symbols.
The dimensional identifiers in 'indexSet' correspond to the loops surrounding 'op' from outermost to innermost.
Definition at line 236 of file AffineAnalysis.cpp.
References mlir::getEnclosingAffineForAndIfOps(), mlir::getIndexSet(), and value.
Referenced by mlir::checkMemrefAccessDependence().
getSupportedReduction()
static Value getSupportedReduction (AffineForOp forOp, unsigned pos, AtomicRMWKind & kind) static
Get the value that is being reduced by pos-th reduction in the loop if such a reduction can be performed by affine parallel loops.
This assumes floating-point operations are commutative. On success, kind will be the reduction kind suitable for use in affine parallel loop builder. If the reduction is not supported, returns null.
Definition at line 41 of file AffineAnalysis.cpp.
References mlir::matchReduction().
Referenced by mlir::getSupportedReductions().
initDependenceConstraints()
static void initDependenceConstraints (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, const ValuePositionMap & valuePosMap, FlatAffineValueConstraints * dependenceConstraints) static
Definition at line 421 of file AffineAnalysis.cpp.
References mlir::AffineValueMap::getAffineMap(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::AffineValueMap::getOperands(), mlir::FlatAffineValueConstraints::getValues(), mlir::FlatAffineValueConstraints::hasValue(), mlir::isForInductionVar(), mlir::isValidSymbol(), mlir::FlatAffineValueConstraints::reset(), mlir::FlatAffineValueConstraints::setValue(), mlir::FlatAffineValueConstraints::setValues(), and value.
Referenced by mlir::checkMemrefAccessDependence().
srcAppearsBeforeDstInAncestralBlock()
static bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, const FlatAffineValueConstraints & srcDomain, unsigned numCommonLoops) static
Definition at line 773 of file AffineAnalysis.cpp.
References getCommonBlock(), and mlir::MemRefAccess::opInst.
Referenced by mlir::checkMemrefAccessDependence().