MLIR: lib/Dialect/Arithmetic/IR/ArithmeticOps.cpp File Reference
ArithmeticOps.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "ArithmeticCanonicalization.inc"
#include "mlir/Dialect/Arithmetic/IR/ArithmeticOps.cpp.inc"
#include "mlir/Dialect/Arithmetic/IR/ArithmeticOpsEnums.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static IntegerAttr addIntegerAttrs (PatternRewriter &builder, Value res, Attribute lhs, Attribute rhs)
static IntegerAttr subIntegerAttrs (PatternRewriter &builder, Value res, Attribute lhs, Attribute rhs)
static arith::CmpIPredicate invertPredicate (arith::CmpIPredicate pred)
Invert an integer comparison predicate.
static arith::CmpIPredicateAttr invertPredicate (arith::CmpIPredicateAttr pred)
static APInt signedCeilNonnegInputs (APInt a, APInt b, bool &overflow)
template<typename ValType , typename Op >
static LogicalResult verifyExtOp (Op op)
template<typename ValType , typename Op >
static LogicalResult verifyTruncateOp (Op op)
static Type getI1SameShape (Type type)
Return the type of the same shape (scalar, vector or tensor) containing i1.
static bool applyCmpPredicateToEqualOperands (arith::CmpIPredicate predicate)
Returns true if the predicate is true for two equal operands.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 779 of file ArithmeticOps.cpp.
Function Documentation
addIntegerAttrs()
static IntegerAttr addIntegerAttrs (PatternRewriter & builder, Value res, Attribute lhs, Attribute rhs) static
Definition at line 24 of file ArithmeticOps.cpp.
References mlir::Attribute::cast(), mlir::Builder::getIntegerAttr(), and mlir::Value::getType().
applyCmpPredicateToEqualOperands()
static bool applyCmpPredicateToEqualOperands (arith::CmpIPredicate predicate) static
Returns true if the predicate is true for two equal operands.
Definition at line 674 of file ArithmeticOps.cpp.
References mlir::arith::applyCmpPredicate(), and mlir::BoolAttr::get().
getI1SameShape()
static Type getI1SameShape (Type type) static
Return the type of the same shape (scalar, vector or tensor) containing i1.
Definition at line 629 of file ArithmeticOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getContext(), mlir::Type::isa(), and vectorType().
invertPredicate() [1/2]
static arith::CmpIPredicate invertPredicate (arith::CmpIPredicate pred) static
Invert an integer comparison predicate.
Definition at line 39 of file ArithmeticOps.cpp.
Referenced by invertPredicate().
invertPredicate() [2/2]
static arith::CmpIPredicateAttr invertPredicate (arith::CmpIPredicateAttr pred) static
Definition at line 65 of file ArithmeticOps.cpp.
References mlir::Builder::getZeroAttr(), mlir::RewritePatternSet::insert(), invertPredicate(), mlir::m_One(), mlir::m_Zero(), and mlir::matchPattern().
signedCeilNonnegInputs()
static APInt signedCeilNonnegInputs (APInt a, APInt b, bool & overflow) static
Definition at line 196 of file ArithmeticOps.cpp.
References mlir::ceil(), mlir::Builder::getZeroAttr(), mlir::RewritePatternSet::insert(), mlir::m_ConstantInt(), mlir::m_Zero(), and mlir::matchPattern().
subIntegerAttrs()
static IntegerAttr subIntegerAttrs (PatternRewriter & builder, Value res, Attribute lhs, Attribute rhs) static
Definition at line 31 of file ArithmeticOps.cpp.
References mlir::Attribute::cast(), mlir::Builder::getIntegerAttr(), and mlir::Value::getType().
verifyExtOp()
template<typename ValType , typename Op > static LogicalResult verifyExtOp (Op op) static
Definition at line 448 of file ArithmeticOps.cpp.
References mlir::Type::cast(), mlir::OpState::emitError(), mlir::getElementTypeOrSelf(), and mlir::success().
verifyTruncateOp()
template<typename ValType , typename Op > static LogicalResult verifyTruncateOp (Op op) static
Definition at line 461 of file ArithmeticOps.cpp.
References mlir::Type::cast(), mlir::OpState::emitError(), mlir::ShapedType::getElementType(), mlir::getElementTypeOrSelf(), mlir::Type::getIntOrFloatBitWidth(), mlir::RewritePatternSet::insert(), mlir::success(), and value.