MLIR: mlir::linalg::detail Namespace Reference
mlir::linalg::detail Namespace Reference
Functions
LogicalResult verifyContractionInterface (Operation *op)
Verify that op conforms to ContractionOpInterface.
LogicalResult verifyConvolutionInterface (Operation *op)
Verify that op conforms to the ConvolutionOpInterface.
LogicalResult verifyStructuredOpInterface (Operation *op)
Verify that op conforms to the invariants of StructuredOpInterface.
Function Documentation
verifyContractionInterface()
LogicalResult mlir::linalg::detail::verifyContractionInterface (Operation * op)
Verify that op conforms to ContractionOpInterface.
Verify that a LinalgOp op is a contraction.
A Linalg contraction is defined in general terms:
Has 2 input and 1 output shapes.
Has at least one reduction dimension.
Has only projected permutation indexing maps.
its body computes u5(u1(c) + u2(u3(a) * u4(b))) on some field (AddOpType, MulOpType), where u1, u2, u3, u4 and u5 represent scalar unary operations that may change the type (e.g. for mixed-precision). As a consequence, when vectorization of such an op occurs, the only special behavior is that the (unique) MulOpType is vectorized into a vector.contract. All other ops are handled in a generic fashion. In the future, we may wish to allow more input arguments and elementwise and constant operations that do not involve the reduction dimension(s).
Definition at line 140 of file LinalgInterfaces.cpp.
References mlir::Operation::emitError(), isContractionInterfaceImpl(), NoReduction, NotAddMul, NotLinalgOp, NotProjectedPermutations, mlir::success(), and WrongNumOperands.
verifyConvolutionInterface()
LogicalResult mlir::linalg::detail::verifyConvolutionInterface (Operation * op)
Verify that op conforms to the ConvolutionOpInterface.
Definition at line 384 of file LinalgInterfaces.cpp.
References mlir::Operation::emitError(), isConvolutionInterfaceImpl(), NonConvolutionLoop, NonOutputDimNotReduction, NotLinalgOp, NotProjectedPermutations, OutputDimsNotParallel, mlir::success(), WrongInputIndexingMap, and WrongNumOperands.
verifyStructuredOpInterface()
LogicalResult mlir::linalg::detail::verifyStructuredOpInterface (Operation * op)
Verify that op conforms to the invariants of StructuredOpInterface.
Definition at line 584 of file LinalgInterfaces.cpp.
References mlir::AffineMap::compose(), mlir::AffineExpr::dyn_cast(), elementType(), mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::Block::getArgument(), mlir::getElementTypeOrSelf(), mlir::Block::getNumArguments(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::Operation::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), mlir::Value::getType(), mlir::ShapedType::isDynamic(), max(), min(), op, mlir::success(), and mlir::OpTrait::impl::verifyNOperands().