MLIR: mlir::arith Namespace Reference
mlir::arith Namespace Reference
Functions
bool applyCmpPredicate (arith::CmpIPredicate predicate, const APInt &lhs, const APInt &rhs)
Compute lhs pred rhs, where pred is one of the known integer comparison predicates.
bool applyCmpPredicate (arith::CmpFPredicate predicate, const APFloat &lhs, const APFloat &rhs)
Compute lhs pred rhs, where pred is one of the known floating point comparison predicates.
Function Documentation
applyCmpPredicate() [1/2]
bool mlir::arith::applyCmpPredicate (arith::CmpIPredicate predicate, const APInt & lhs, const APInt & rhs)
Compute lhs pred rhs, where pred is one of the known integer comparison predicates.
Definition at line 646 of file ArithmeticOps.cpp.
Referenced by applyCmpPredicate(), and applyCmpPredicateToEqualOperands().
applyCmpPredicate() [2/2]
bool mlir::arith::applyCmpPredicate (arith::CmpFPredicate predicate, const APFloat & lhs, const APFloat & rhs)
Compute lhs pred rhs, where pred is one of the known floating point comparison predicates.
Definition at line 716 of file ArithmeticOps.cpp.
References applyCmpPredicate(), and mlir::BoolAttr::get().