MLIR: lib/Dialect/Math/Transforms/PolynomialApproximation.cpp File Reference
PolynomialApproximation.cpp File Reference
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Math/Transforms/Passes.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Transforms/Bufferize.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include <climits>
Macros
#define LN2_VALUE 0.693147180559945309417232121458176568075500134360255254120680009493393621L
#define LOG2E_VALUE 1.442695040888963407359924681001892137426645954152985934135449406931109219L
#define TWO_OVER_PI 0.6366197723675813430755350534900574481378385829618257949906693762L
#define PI_OVER_2 1.5707963267948966192313216916397514420985846996875529104874722961L
Typedefs
using TypePredicate = llvm::function_ref< bool(Type)>
Functions
static Optional< int > vectorWidth (Type type, TypePredicate pred)
static int vectorWidth (Type type)
static LLVM_ATTRIBUTE_UNUSED Type elementType (Type type)
static LLVM_ATTRIBUTE_UNUSED bool isF32 (Type type)
static LLVM_ATTRIBUTE_UNUSED bool isI32 (Type type)
static Type broadcast (Type type, int width)
static Value broadcast (ImplicitLocOpBuilder &builder, Value value, int width)
static Value f32Cst (ImplicitLocOpBuilder &builder, float value)
static Value i32Cst (ImplicitLocOpBuilder &builder, int32_t value)
static Value f32FromBits (ImplicitLocOpBuilder &builder, uint32_t bits)
static Value min (ImplicitLocOpBuilder &builder, Value a, Value b)
static Value max (ImplicitLocOpBuilder &builder, Value a, Value b)
static Value clamp (ImplicitLocOpBuilder &builder, Value value, Value lowerBound, Value upperBound)
static std::pair< Value, Value > frexp (ImplicitLocOpBuilder &builder, Value arg, bool is_positive=false)
static Value exp2I32 (ImplicitLocOpBuilder &builder, Value arg)
Macro Definition Documentation
LN2_VALUE
#define LN2_VALUE 0.693147180559945309417232121458176568075500134360255254120680009493393621L
Definition at line 260 of file PolynomialApproximation.cpp.
LOG2E_VALUE
#define LOG2E_VALUE 1.442695040888963407359924681001892137426645954152985934135449406931109219L
Definition at line 262 of file PolynomialApproximation.cpp.
PI_OVER_2
#define PI_OVER_2 1.5707963267948966192313216916397514420985846996875529104874722961L
Definition at line 647 of file PolynomialApproximation.cpp.
TWO_OVER_PI
#define TWO_OVER_PI 0.6366197723675813430755350534900574481378385829618257949906693762L
Definition at line 645 of file PolynomialApproximation.cpp.
Typedef Documentation
TypePredicate
using TypePredicate = llvm::function_ref<bool(Type)>
Definition at line 27 of file PolynomialApproximation.cpp.
Function Documentation
broadcast() [1/2]
static Type broadcast (Type type, int width) static
Definition at line 69 of file PolynomialApproximation.cpp.
References mlir::Type::isa().
Referenced by broadcast(), exp2I32(), and frexp().
broadcast() [2/2]
static Value broadcast (ImplicitLocOpBuilder & builder, Value value, int width) static
Definition at line 75 of file PolynomialApproximation.cpp.
References broadcast(), mlir::ImplicitLocOpBuilder::create(), mlir::Value::getType(), mlir::Type::isa(), and value.
clamp()
static Value clamp (ImplicitLocOpBuilder & builder, Value value, Value lowerBound, Value upperBound) static
Definition at line 114 of file PolynomialApproximation.cpp.
References max(), and min().
Referenced by createLinalgBodyCalculationForElementwiseOp(), exp2I32(), and reduceMatchAndRewriteHelper().
elementType()
static LLVM_ATTRIBUTE_UNUSED Type elementType (Type type) static
Definition at line 53 of file PolynomialApproximation.cpp.
References mlir::Type::dyn_cast(), and vectorType().
Referenced by acceptBitWidth(), buildSequentialConstant(), checkTensorElementType(), mlir::pdl::PDLType::classof(), mlir::ShapedType::clone(), convertArrayType(), convertBoolMemrefType(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), convertMemrefType(), convertRuntimeArrayType(), convertScalableVectorTypeToLLVM(), convertStructTypePacked(), convertStructTypeWithOffset(), convertVectorType(), mlir::VulkanLayoutUtils::decorateType(), diag(), exp2I32(), mlir::DenseElementsAttr::float_value_begin(), mlir::DenseElementsAttr::float_value_end(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), frexp(), fuseWithReshapeByExpansion(), genBuffers(), mlir::LLVM::LLVMArrayType::get(), mlir::gpu::MMAMatrixType::get(), mlir::spirv::ArrayType::get(), mlir::spirv::RuntimeArrayType::get(), mlir::LLVM::LLVMFixedVectorType::get(), mlir::LLVM::LLVMScalableVectorType::get(), mlir::spirv::CooperativeMatrixNVType::get(), getBitWidth(), mlir::OpTrait::util::getBroadcastedType(), mlir::spirv::StructType::getCapabilities(), mlir::LLVM::LLVMArrayType::getChecked(), mlir::gpu::MMAMatrixType::getChecked(), mlir::LLVM::LLVMFixedVectorType::getChecked(), mlir::LLVM::LLVMScalableVectorType::getChecked(), mlir::ConvertToLLVMPattern::getElementPtrType(), mlir::LLVM::LLVMFixedVectorType::getElementType(), mlir::LLVM::LLVMScalableVectorType::getElementType(), mlir::spirv::StructType::getExtensions(), mlir::DenseElementsAttr::getFloatValues(), mlir::LLVM::detail::getLLVMConstant(), getMemRefEltSizeInBytes(), mlir::getMemRefSizeInBytes(), mlir::LLVMTypeConverter::getPointerBitwidth(), mlir::quant::QuantizedType::getQuantizedElementType(), mlir::getReductionOp(), mlir::spirv::ArrayType::getSizeInBytes(), getSrcVectorElementType(), mlir::LLVMTypeConverter::getUnrankedMemRefDescriptorSize(), mlir::ShapedType::hasStaticShape(), isAllocationSupported(), isAsyncWithOneDependency(), mlir::LLVM::isCompatibleVectorType(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), UnrollOuterMultiReduction::matchAndRewrite(), mlir::MemRefType::Builder::operator MemRefType(), mlir::spirv::detail::ArrayTypeStorage::operator==(), mlir::gpu::MMAMatrixStorageType::operator==(), mlir::spirv::detail::CooperativeMatrixTypeStorage::operator==(), mlir::spirv::detail::ImageTypeStorage::operator==(), mlir::LLVM::detail::LLVMTypeAndSizeStorage::operator==(), mlir::spirv::detail::RuntimeArrayTypeStorage::operator==(), parseArrayType(), mlir::detail::Parser::parseComplexType(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseElementAttrHexValues(), parseExtractValueOp(), parseLoadOp(), mlir::detail::Parser::parseMemRefType(), parseRuntimeArrayType(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), mlir::detail::Parser::parseTensorType(), mlir::detail::Parser::parseVectorType(), mlir::AsmPrinter::Impl::printDenseIntOrFPElementsAttr(), replaceUnitExtents(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), mlir::MemRefType::Builder::setElementType(), mlir::vector::splitFullAndPartialTransfer(), vectorizeAffineLoad(), mlir::LLVM::LLVMArrayType::verify(), mlir::LLVM::LLVMFixedVectorType::verify(), mlir::LLVM::LLVMScalableVectorType::verify(), verify(), verifyAtomicUpdateOp(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::linalg::detail::verifyStructuredOpInterface(), verifyTransferOp(), verifyYield(), and writeAPIntsToBuffer().
exp2I32()
static Value exp2I32 (ImplicitLocOpBuilder & builder, Value arg) static
Definition at line 160 of file PolynomialApproximation.cpp.
References broadcast(), clamp(), mlir::ImplicitLocOpBuilder::create(), elementType(), f32Cst(), mlir::Builder::getF32Type(), mlir::Operation::getLoc(), mlir::Value::getType(), i32Cst(), isF32(), isI32(), mlir::RewriterBase::notifyMatchFailure(), op, mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::RewriterBase::replaceOp(), rewriter, mlir::success(), value, and vectorWidth().
f32Cst()
static Value f32Cst (ImplicitLocOpBuilder & builder, float value) static
Definition at line 85 of file PolynomialApproximation.cpp.
References mlir::ImplicitLocOpBuilder::create(), mlir::Builder::getF32FloatAttr(), and mlir::Builder::getF32Type().
Referenced by exp2I32(), and frexp().
f32FromBits()
static Value f32FromBits (ImplicitLocOpBuilder & builder, uint32_t bits) static
Definition at line 95 of file PolynomialApproximation.cpp.
References mlir::ImplicitLocOpBuilder::create(), mlir::Builder::getF32Type(), and i32Cst().
Referenced by frexp().
frexp()
static std::pair<Value, Value> frexp (ImplicitLocOpBuilder & builder, Value arg, bool is_positive = false) static
Definition at line 121 of file PolynomialApproximation.cpp.
References broadcast(), mlir::ImplicitLocOpBuilder::create(), elementType(), f32Cst(), f32FromBits(), mlir::Builder::getF32Type(), mlir::Builder::getIntegerType(), mlir::Value::getType(), i32Cst(), isF32(), value, and vectorWidth().
Referenced by computeMultiplierAndShiftTosaScale16(), and computeMultiplierAndShiftTosaScale32().
i32Cst()
static Value i32Cst (ImplicitLocOpBuilder & builder, int32_t value) static
Definition at line 90 of file PolynomialApproximation.cpp.
References mlir::ImplicitLocOpBuilder::create(), mlir::Builder::getI32IntegerAttr(), and mlir::Builder::getI32Type().
Referenced by exp2I32(), f32FromBits(), and frexp().
isF32()
static LLVM_ATTRIBUTE_UNUSED bool isF32 (Type type) static
Definition at line 58 of file PolynomialApproximation.cpp.
References mlir::Type::isF32().
Referenced by exp2I32(), frexp(), and mlir::FloatType::scaleElementBitwidth().
isI32()
static LLVM_ATTRIBUTE_UNUSED bool isI32 (Type type) static
Definition at line 60 of file PolynomialApproximation.cpp.
References mlir::Type::isInteger().
Referenced by exp2I32().
max()
static Value max (ImplicitLocOpBuilder & builder, Value a, Value b) static
Definition at line 109 of file PolynomialApproximation.cpp.
References mlir::ImplicitLocOpBuilder::create().
Referenced by adjustToDivisorsOfTripCounts(), mlir::tosa::buildQTypeFromMinMax(), checkAndUpdateCapabilityRequirements(), clamp(), clampHelper(), computeDirectionVector(), computeMultiplierAndShiftTosaScale16(), computeMultiplierAndShiftTosaScale32(), mlir::concatAffineMaps(), mlir::createAffineDataCopyGenerationPass(), createLinalgBodyCalculationForElementwiseOp(), declareReduction(), mlir::VulkanLayoutUtils::decorateType(), doSequentialDispatch(), mlir::detail::OperandStorage::eraseOperands(), executeGetOperandsResults(), foldExtractStridedOpFromInsertChain(), generateFusedElementwiseOpRegion(), mlir::quant::CalibratedQuantizedType::get(), mlir::quant::CalibratedQuantizedType::getChecked(), getDefaultStorageParams(), mlir::NestedPattern::getDepth(), mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::getHashValue(), mlir::getInnermostCommonLoopDepth(), mlir::getLargestDivisorOfTripCount(), getLLVMAtomicBinOp(), getLocationFromLoc(), getMaxDimAndSymbol(), getMaxPosOfType(), getMemRefOpAlignment(), mlir::detail::PassOptions::getOptionWidth(), getTypeNumBytes(), isFusionProfitable(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), mlir::AffineMap::isPermutationOfMinorIdentityWithBroadcasting(), isSumOfIntegerArrayAttrConfinedToShape(), mlir::ConversionPattern::matchAndRewrite(), matchSimpleAtomicOp(), mlir::Matrix::Matrix(), parseAndVerifyInteger(), parseCalibratedType(), printPassEntry(), printTimeHeader(), reduceMatchAndRewriteHelper(), mlir::FlatAffineConstraints::removeIdRange(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::OpTrait::util::staticallyKnownBroadcastable(), mlir::substWithMin(), mlir::raw_indented_ostream::unindent(), mlir::FlatAffineConstraints::unionBoundingBox(), verify(), mlir::linalg::detail::verifyStructuredOpInterface(), and mlir::quant::UniformQuantizedValueConverter::~UniformQuantizedValueConverter().
min()
static Value min (ImplicitLocOpBuilder & builder, Value a, Value b) static
Definition at line 104 of file PolynomialApproximation.cpp.
References mlir::ImplicitLocOpBuilder::create().
Referenced by addOrderingConstraints(), mlir::tosa::buildQTypeFromMinMax(), clamp(), clampHelper(), collectFusableLoops(), computeDirectionVector(), createLinalgBodyCalculationForElementwiseOp(), declareReduction(), mlir::failableParallelForEach(), foldExtractStridedOpFromInsertChain(), genLocals(), mlir::quant::CalibratedQuantizedType::get(), getBestIdToEliminate(), mlir::quant::CalibratedQuantizedType::getChecked(), mlir::getConstantTripCount(), getDefaultStorageParams(), mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::getHashValue(), mlir::getInnermostCommonLoopDepth(), getLLVMAtomicBinOp(), getMaxLoopDepth(), mlir::detail::OpResultImpl::getNextResultAtOffset(), getNumCommonLoops(), mlir::getNumCommonSurroundingLoops(), mlir::linalg::getSmallestBoundingIndex(), isIntegerArrayAttrConfinedToShape(), isSumOfIntegerArrayAttrConfinedToShape(), mlir::ConversionPattern::matchAndRewrite(), matchSimpleAtomicOp(), parseCalibratedType(), reduceMatchAndRewriteHelper(), mlir::FlatAffineConstraints::removeIdRange(), sliceTransferIndices(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::substWithMin(), mlir::FlatAffineConstraints::unionBoundingBox(), verify(), mlir::linalg::detail::verifyStructuredOpInterface(), and mlir::quant::UniformQuantizedValueConverter::~UniformQuantizedValueConverter().
vectorWidth() [1/2]
static Optional<int> vectorWidth (Type type, TypePredicate pred) static
Definition at line 31 of file PolynomialApproximation.cpp.
References mlir::Type::dyn_cast(), mlir::vector::None, and vectorType().
Referenced by exp2I32(), and frexp().
vectorWidth() [2/2]
static int vectorWidth (Type type) static
Definition at line 47 of file PolynomialApproximation.cpp.
References mlir::Type::dyn_cast(), and vectorType().