MLIR: lib/Dialect/SparseTensor/Transforms/Sparsification.cpp File Reference
Sparsification.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SCF/Transforms.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Dialect/SparseTensor/Utils/Merger.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/TensorEncoding.h"
#include "llvm/ADT/SmallBitVector.h"
Enumerations
enum SortMask
enum Reduction
Functions
static unsigned perm (const SparseTensorEncodingAttr &enc, unsigned d)
Helper method to apply dimension ordering permutation.
static Dim toDim (const SparseTensorEncodingAttr &enc, unsigned d)
Helper method to translate dim level type to internal representation.
static bool findAffine (Merger &merger, unsigned tensor, AffineExpr a, Dim dim, bool isDense)
Helper method to inspect affine expressions.
static bool findSparseAnnotations (Merger &merger, linalg::GenericOp op)
Helper method to inspect sparse encodings in the tensor types.
static bool topSortDFS (unsigned i, std::vector< unsigned > &visit, std::vector< unsigned > &topSort, std::vector< std::vector< bool >> &adjM)
A DFS helper to compute a topological sort.
static void addAffineOrderings (std::vector< std::vector< bool >> &adjM, AffineExpr a, AffineExpr b, unsigned fidx)
Helper method to add all constraints from the indices in one affine expression before all indices in the other affine expression.
static bool computeIterationGraph (Merger &merger, linalg::GenericOp op, std::vector< unsigned > &topSort, unsigned mask)
Computes a topologically sorted iteration graph for the linalg operation.
static bool isAdmissableTensorExp (Merger &merger, linalg::GenericOp op, unsigned exp)
Returns true when the tensor expression is admissable for codegen.
static StringRef getReductionName (Reduction kind)
Maps reduction kind to name encoding.
static Reduction getReduction (Kind kind)
Maps operation to reduction.
static Value genReductionInit (PatternRewriter &rewriter, Location loc, Reduction kind, VectorType vtp, Value r)
Generates an initial value for a vector reductions, following the scheme given in Chapter 5 of "The Software Vectorization Handbook", where the initial scalar value is correctly embedded in the vector reduction value, and a straightforward horizontal reduction will complete the operation.
static Type genIntType (PatternRewriter &rewriter, unsigned width)
Maps sparse integer option to actual integral storage type.
static bool getInPlace (Value val)
Detects in-place annotation on tensor argument.
static Value genOutputBuffer (CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, MemRefType denseTp, ArrayRef< Value > args)
Generates buffer for the output tensor.
static bool genBuffers (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op)
Local bufferization of all dense and sparse data structures.
static VectorType vectorType (CodeGen &codegen, Type etp)
Constructs vector type.
static VectorType vectorType (CodeGen &codegen, Value ptr)
Constructs vector type from pointer.
static Value genVectorMask (CodeGen &codegen, PatternRewriter &rewriter, Value iv, Value lo, Value hi, Value step)
Constructs vector iteration mask.
static Value genVectorLoad (CodeGen &codegen, PatternRewriter &rewriter, Value ptr, ArrayRef< Value > args)
Generates a vectorized load lhs = a[ind[lo:hi]] or lhs = a[lo:hi].
static void genVectorStore (CodeGen &codegen, PatternRewriter &rewriter, Value rhs, Value ptr, ArrayRef< Value > args)
Generates a vectorized store a[ind[lo:hi]] = rhs or a[lo:hi] = rhs.
static Value genVectorInvariantValue (CodeGen &codegen, PatternRewriter &rewriter, Value val)
Generates a vectorized invariant.
static Value genAffine (CodeGen &codegen, PatternRewriter &rewriter, AffineExpr a, Location loc)
Generates an affine expression.
static Value genSubscript (CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, OpOperand *t, SmallVector< Value, 4 > &args)
Generates subscript for load/store on a dense or sparse tensor.
static Value genTensorLoad (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, unsigned exp)
Generates a load on a dense or sparse tensor.
static void genTensorStore (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, Value rhs)
Generates a store on a dense or sparse tensor.
static Value genLoad (CodeGen &codegen, PatternRewriter &rewriter, Location loc, Value ptr, Value s)
Generates a pointer/index load from the sparse storage scheme.
static Value genInvariantValue (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, unsigned exp)
Generates an invariant value.
static Value genAddress (CodeGen &codegen, PatternRewriter &rewriter, Location loc, Value size, Value p, Value i)
Generates an address computation "sz * p + i".
static Value genReductionStart (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op)
Generates start of a reduction.
static void genReductionEnd (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op)
Generates end of a reduction.
static Value genExp (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, unsigned exp)
Recursively generates tensor expression.
static bool isInvariantAffine (const CodeGen &codegen, AffineExpr a, unsigned ldx, bool &atLevel)
Determines if affine expression is invariant.
static void genInvariants (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, unsigned exp, unsigned ldx, bool hoist, Kind last=Kind::kTensor)
Hoists loop invariant tensor loads for which indices have been exhausted.
static bool genInit (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, std::vector< unsigned > &topSort, unsigned at, llvm::BitVector &inits)
Generates initialization code for the subsequent loop sequence at current index level.
static bool isVectorFor (CodeGen &codegen, bool isInner, bool isSparse)
Returns vectorization strategy.
static bool isParallelFor (CodeGen &codegen, bool isOuter, bool isReduction, bool isSparse, bool isVector)
Returns parallelization strategy.
static bool denseUnitStrides (Merger &merger, linalg::GenericOp op, unsigned ldx)
Checks unit strides for dense tensors.
static Operation * genFor (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, bool isOuter, bool isInner, unsigned idx, llvm::BitVector &indices)
Generates a for-loop on a single index.
static Operation * genWhile (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, unsigned idx, bool needsUniv, llvm::BitVector &indices)
Emit a while-loop for co-iteration over multiple indices.
static Operation * genLoop (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, std::vector< unsigned > &topSort, unsigned at, bool needsUniv, llvm::BitVector &indices)
Generates a for-loop or a while-loop, depending on whether it implements singleton iteration or co-iteration over the given conjunction.
static void genLocals (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, std::vector< unsigned > &topSort, unsigned at, bool needsUniv, llvm::BitVector &locals)
Generates the local variables for this loop, consisting of the sparse indices, restored universal dense index, and dense positions.
static void genWhileInduction (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, unsigned idx, bool needsUniv, llvm::BitVector &induction, ResultRange results)
Generates the induction structure for a while-loop.
static scf::IfOp genIf (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, unsigned idx, llvm::BitVector &conditions)
Generates a single if-statement within a while-loop.
static void genStmt (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op, std::vector< unsigned > &topSort, unsigned exp, unsigned at)
Recursively generates code while computing iteration lattices in order to manage the complexity of implementing co-iteration over unions and intersections of sparse iterations spaces.
static void genResult (Merger &merger, CodeGen &codegen, PatternRewriter &rewriter, linalg::GenericOp op)
Converts the result computed by the sparse kernel into the required form.
Enumeration Type Documentation
Reduction
enum Reduction
Definition at line 41 of file Sparsification.cpp.
SortMask
enum SortMask
Definition at line 38 of file Sparsification.cpp.
Function Documentation
addAffineOrderings()
static void addAffineOrderings (std::vector< std::vector< bool >> & adjM, AffineExpr a, AffineExpr b, unsigned fidx) static
Helper method to add all constraints from the indices in one affine expression before all indices in the other affine expression.
For example i0+i1 < i2+i3+1 yields i0<i2, i0<i3, i1<i2, and i1<i3.
Definition at line 187 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::DimId, mlir::AffineExpr::getKind(), and mlir::Mul.
Referenced by computeIterationGraph().
computeIterationGraph()
static bool computeIterationGraph (Merger & merger, linalg::GenericOp op, std::vector< unsigned > & topSort, unsigned mask) static
Computes a topologically sorted iteration graph for the linalg operation.
Ensures all tensors are visited in natural index order. This is essential for sparse storage formats since these only support access along fixed dimensions. Even for dense storage formats, however, the natural index order yields innermost unit-stride access with better spatial locality.
Definition at line 215 of file Sparsification.cpp.
References addAffineOrderings(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::kSparse, mlir::sparse_tensor::kUndef, map(), perm(), and topSortDFS().
Referenced by genResult().
denseUnitStrides()
static bool denseUnitStrides (Merger & merger, linalg::GenericOp op, unsigned ldx) static
Checks unit strides for dense tensors.
The iteration graph may have ignored dense access patterns in order to avoid cycles (sparse access patterns are always placed innermost), but that means dense access has become strided. For now, we reject vectorization of such cases. TODO: implement strided load/stores on dense arrays
Definition at line 937 of file Sparsification.cpp.
References mlir::AffineExpr::cast(), mlir::DimId, mlir::AffineExpr::getKind(), mlir::sparse_tensor::getSparseTensorEncoding(), and map().
Referenced by genFor().
findAffine()
static bool findAffine (Merger & merger, unsigned tensor, AffineExpr a, Dim dim, bool isDense) static
Helper method to inspect affine expressions.
Rejects cases where the same index is used in more than one dimension of a tensor. Also rejects affine expressions that are not a direct index for annotated tensors. TODO: accept more affine cases for sparse tensors
Definition at line 118 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::Constant, mlir::DimId, mlir::AffineExpr::getKind(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::kUndef, mlir::Mul, and mlir::sparse_tensor::Merger::setDim().
Referenced by findSparseAnnotations().
findSparseAnnotations()
static bool findSparseAnnotations (Merger & merger, linalg::GenericOp op) static
Helper method to inspect sparse encodings in the tensor types.
Fills the per-dimension sparsity information for all tensors. Returns true if the sparse annotations and affine subscript expressions of all tensors are admissable. Returns false if no annotations are found or inadmissable constructs occur.
Definition at line 148 of file Sparsification.cpp.
References findAffine(), mlir::sparse_tensor::getSparseTensorEncoding(), map(), perm(), and toDim().
Referenced by genResult().
genAddress()
static Value genAddress (CodeGen & codegen, PatternRewriter & rewriter, Location loc, Value size, Value p, Value i) static
Generates an address computation "sz * p + i".
Definition at line 734 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), genVectorInvariantValue(), mlir::Value::getType(), and loc.
Referenced by genLocals().
genAffine()
static Value genAffine (CodeGen & codegen, PatternRewriter & rewriter, AffineExpr a, Location loc) static
Generates an affine expression.
Definition at line 585 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::Constant, mlir::OpBuilder::create(), mlir::DimId, mlir::AffineExpr::getKind(), loc, and mlir::Mul.
Referenced by genSubscript().
genBuffers()
static bool genBuffers (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op) static
Local bufferization of all dense and sparse data structures.
This code enables testing the first prototype sparse compiler.
Definition at line 431 of file Sparsification.cpp.
References mlir::AffineExpr::cast(), mlir::OpBuilder::create(), mlir::linalg::createOrFoldDimOp(), mlir::DimId, elementType(), genIntType(), genOutputBuffer(), mlir::getElementTypeOrSelf(), getInPlace(), mlir::AffineExpr::getKind(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::Merger::isDim(), mlir::ShapedType::kDynamicSize, mlir::sparse_tensor::kSparse, loc, map(), and perm().
Referenced by genResult().
genExp()
static Value genExp (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, unsigned exp) static
Recursively generates tensor expression.
Definition at line 782 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::buildExp(), mlir::sparse_tensor::TensorExp::children, mlir::sparse_tensor::Children::e0, mlir::sparse_tensor::Children::e1, mlir::sparse_tensor::Merger::exp(), genInvariantValue(), genTensorLoad(), mlir::sparse_tensor::TensorExp::kind, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kTensor, and loc.
Referenced by genStmt().
genFor()
static Operation* genFor (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, bool isOuter, bool isInner, unsigned idx, llvm::BitVector & indices) static
Generates a for-loop on a single index.
Definition at line 956 of file Sparsification.cpp.
References mlir::OpBuilder::create(), denseUnitStrides(), mlir::sparse_tensor::Merger::exp(), genReductionStart(), genVectorMask(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::Merger::isDim(), isParallelFor(), mlir::isReductionIterator(), isVectorFor(), mlir::sparse_tensor::kSparse, loc, mlir::OpBuilder::setInsertionPointToStart(), mlir::sparse_tensor::Merger::tensor(), and mlir::sparse_tensor::TensorExp::val.
Referenced by genLoop().
genIf()
static scf::IfOp genIf (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, unsigned idx, llvm::BitVector & conditions) static
Generates a single if-statement within a while-loop.
Definition at line 1177 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::kSparse, loc, mlir::OpBuilder::setInsertionPointToStart(), and mlir::sparse_tensor::Merger::tensor().
Referenced by genStmt().
genInit()
static bool genInit (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, std::vector< unsigned > & topSort, unsigned at, llvm::BitVector & inits) static
Generates initialization code for the subsequent loop sequence at current index level.
Returns true if the loop sequence needs to maintain the universal index.
Definition at line 859 of file Sparsification.cpp.
References mlir::OpBuilder::create(), genLoad(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::kSparse, loc, and mlir::sparse_tensor::Merger::tensor().
Referenced by genStmt().
genIntType()
static Type genIntType (PatternRewriter & rewriter, unsigned width) static
Maps sparse integer option to actual integral storage type.
Definition at line 376 of file Sparsification.cpp.
References mlir::Builder::getIndexType(), and mlir::Builder::getIntegerType().
Referenced by genBuffers().
genInvariants()
static void genInvariants (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, unsigned exp, unsigned ldx, bool hoist, Kind last = Kind::kTensor) static
Hoists loop invariant tensor loads for which indices have been exhausted.
Definition at line 818 of file Sparsification.cpp.
References mlir::sparse_tensor::TensorExp::children, mlir::sparse_tensor::Children::e0, mlir::sparse_tensor::Children::e1, mlir::sparse_tensor::Merger::exp(), genTensorLoad(), mlir::IROperand< DerivedT, IRValueT >::get(), getReduction(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), isInvariantAffine(), mlir::sparse_tensor::TensorExp::kind, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kTensor, map(), perm(), mlir::sparse_tensor::TensorExp::tensor, and mlir::sparse_tensor::TensorExp::val.
Referenced by genStmt().
genInvariantValue()
static Value genInvariantValue (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, unsigned exp) static
Generates an invariant value.
Definition at line 725 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::exp(), genVectorInvariantValue(), and mlir::sparse_tensor::TensorExp::val.
Referenced by genExp().
genLoad()
static Value genLoad (CodeGen & codegen, PatternRewriter & rewriter, Location loc, Value ptr, Value s) static
Generates a pointer/index load from the sparse storage scheme.
Narrower data types need to be zero extended before casting the value into the index type used for looping and indexing.
Definition at line 681 of file Sparsification.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), genVectorLoad(), getElementType(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Value::getType(), mlir::Type::isa(), loc, and vectorType().
Referenced by genInit(), and genLocals().
genLocals()
static void genLocals (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, std::vector< unsigned > & topSort, unsigned at, bool needsUniv, llvm::BitVector & locals) static
Generates the local variables for this loop, consisting of the sparse indices, restored universal dense index, and dense positions.
Definition at line 1091 of file Sparsification.cpp.
References mlir::OpBuilder::create(), genAddress(), genLoad(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::Merger::isOutTensor(), mlir::sparse_tensor::kDense, mlir::sparse_tensor::kSparse, loc, min(), and mlir::sparse_tensor::Merger::tensor().
Referenced by genStmt().
genLoop()
static Operation* genLoop (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, std::vector< unsigned > & topSort, unsigned at, bool needsUniv, llvm::BitVector & indices) static
Generates a for-loop or a while-loop, depending on whether it implements singleton iteration or co-iteration over the given conjunction.
Definition at line 1074 of file Sparsification.cpp.
References genFor(), genReductionEnd(), and genWhile().
Referenced by genStmt().
genOutputBuffer()
static Value genOutputBuffer (CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, MemRefType denseTp, ArrayRef< Value > args) static
Generates buffer for the output tensor.
Note that all sparse kernels assume that when all elements are written to (viz. x(i) = y(i) * z(i)), the output buffer is already initialized to all zeroes and only nonzeroes values are computed and written out. For updates (viz. x(i) += y(i) * z(i)), only nonzeroes values are used for the updates and no assumption on the original contents of the output buffer is necessary..
Definition at line 398 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::Value::getDefiningOp(), getInPlace(), mlir::Builder::getZeroAttr(), and loc.
Referenced by genBuffers().
genReductionEnd()
static void genReductionEnd (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op) static
Generates end of a reduction.
Definition at line 764 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::sparse_tensor::Merger::exp(), genTensorStore(), getReductionName(), mlir::Builder::getStringAttr(), mlir::Value::getType(), kind, and mlir::sparse_tensor::TensorExp::val.
Referenced by genLoop(), and genStmt().
genReductionInit()
static Value genReductionInit (PatternRewriter & rewriter, Location loc, Reduction kind, VectorType vtp, Value r) static
Generates an initial value for a vector reductions, following the scheme given in Chapter 5 of "The Software Vectorization Handbook", where the initial scalar value is correctly embedded in the vector reduction value, and a straightforward horizontal reduction will complete the operation.
Definition at line 345 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::DenseElementsAttr::get(), mlir::Builder::getFloatAttr(), mlir::Builder::getIntegerAttr(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), and loc.
Referenced by genReductionStart().
genReductionStart()
static Value genReductionStart (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op) static
Generates start of a reduction.
Definition at line 745 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::exp(), genReductionInit(), genTensorLoad(), mlir::sparse_tensor::TensorExp::val, and vectorType().
Referenced by genFor().
genResult()
static void genResult (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op) static
Converts the result computed by the sparse kernel into the required form.
Definition at line 1297 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), mlir::AffineExpr::cast(), computeIterationGraph(), mlir::OpBuilder::create(), mlir::DimId, mlir::failure(), findSparseAnnotations(), genBuffers(), genStmt(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::AffineExpr::getKind(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), isAdmissableTensorExp(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::kSparse, loc, map(), op, options, perm(), mlir::RewriterBase::replaceOp(), rewriter, and mlir::success().
genStmt()
static void genStmt (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, std::vector< unsigned > & topSort, unsigned exp, unsigned at) static
Recursively generates code while computing iteration lattices in order to manage the complexity of implementing co-iteration over unions and intersections of sparse iterations spaces.
Definition at line 1205 of file Sparsification.cpp.
References mlir::sparse_tensor::LatPoint::bits, mlir::sparse_tensor::Merger::buildLattices(), mlir::OpBuilder::create(), mlir::sparse_tensor::LatPoint::exp, genExp(), genIf(), genInit(), genInvariants(), genLocals(), genLoop(), genReductionEnd(), genTensorStore(), genWhileInduction(), mlir::Operation::getResult(), mlir::sparse_tensor::Merger::hasAnyDimOf(), mlir::sparse_tensor::kSparse, mlir::sparse_tensor::Merger::lat(), mlir::sparse_tensor::Merger::latGT(), loc, mlir::sparse_tensor::Merger::optimizeSet(), mlir::sparse_tensor::Merger::set(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::sparse_tensor::LatPoint::simple.
Referenced by genResult().
genSubscript()
static Value genSubscript (CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, OpOperand * t, SmallVector< Value, 4 > & args) static
Generates subscript for load/store on a dense or sparse tensor.
Definition at line 614 of file Sparsification.cpp.
References genAffine(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), map(), and perm().
Referenced by genTensorLoad(), and genTensorStore().
genTensorLoad()
static Value genTensorLoad (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, unsigned exp) static
Generates a load on a dense or sparse tensor.
Definition at line 637 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::Merger::exp(), genSubscript(), genVectorInvariantValue(), genVectorLoad(), mlir::Value::getType(), mlir::Type::isa(), mlir::sparse_tensor::TensorExp::tensor, and mlir::sparse_tensor::TensorExp::val.
Referenced by genExp(), genInvariants(), and genReductionStart().
genTensorStore()
static void genTensorStore (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, Value rhs) static
Generates a store on a dense or sparse tensor.
Definition at line 657 of file Sparsification.cpp.
References mlir::OpBuilder::create(), genSubscript(), and genVectorStore().
Referenced by genReductionEnd(), and genStmt().
genVectorInvariantValue()
static Value genVectorInvariantValue (CodeGen & codegen, PatternRewriter & rewriter, Value val) static
Generates a vectorized invariant.
Here we rely on subsequent loop optimizations to hoist the invariant broadcast out of the vector loop.
Definition at line 575 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::Value::getLoc(), mlir::Value::getType(), and vectorType().
Referenced by genAddress(), genInvariantValue(), and genTensorLoad().
genVectorLoad()
static Value genVectorLoad (CodeGen & codegen, PatternRewriter & rewriter, Value ptr, ArrayRef< Value > args) static
Generates a vectorized load lhs = a[ind[lo:hi]] or lhs = a[lo:hi].
Definition at line 541 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::Value::getLoc(), mlir::Builder::getZeroAttr(), loc, and vectorType().
Referenced by genLoad(), and genTensorLoad().
genVectorMask()
static Value genVectorMask (CodeGen & codegen, PatternRewriter & rewriter, Value iv, Value lo, Value hi, Value step) static
Constructs vector iteration mask.
Definition at line 510 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getAffineSymbolExpr(), mlir::Builder::getContext(), mlir::Builder::getIntegerType(), mlir::Value::getLoc(), loc, mlir::m_Constant(), mlir::matchPattern(), and vectorType().
Referenced by genFor().
genVectorStore()
static void genVectorStore (CodeGen & codegen, PatternRewriter & rewriter, Value rhs, Value ptr, ArrayRef< Value > args) static
Generates a vectorized store a[ind[lo:hi]] = rhs or a[lo:hi] = rhs.
Definition at line 558 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::Value::getLoc(), and loc.
Referenced by genTensorStore().
genWhile()
static Operation* genWhile (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, unsigned idx, bool needsUniv, llvm::BitVector & indices) static
Emit a while-loop for co-iteration over multiple indices.
Definition at line 1019 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Block::getArgument(), mlir::Builder::getIndexType(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::kSparse, loc, mlir::OpBuilder::setInsertionPointToStart(), and mlir::sparse_tensor::Merger::tensor().
Referenced by genLoop().
genWhileInduction()
static void genWhileInduction (Merger & merger, CodeGen & codegen, PatternRewriter & rewriter, linalg::GenericOp op, unsigned idx, bool needsUniv, llvm::BitVector & induction, ResultRange results) static
Generates the induction structure for a while-loop.
Definition at line 1147 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::Merger::isDim(), mlir::sparse_tensor::kSparse, loc, and mlir::sparse_tensor::Merger::tensor().
Referenced by genStmt().
getInPlace()
static bool getInPlace (Value val) static
Detects in-place annotation on tensor argument.
Definition at line 383 of file Sparsification.cpp.
References mlir::Value::dyn_cast().
Referenced by genBuffers(), and genOutputBuffer().
getReduction()
static Reduction getReduction (Kind kind) static
Maps operation to reduction.
Definition at line 320 of file Sparsification.cpp.
References mlir::sparse_tensor::kAddF, mlir::sparse_tensor::kAddI, mlir::sparse_tensor::kAndI, mlir::sparse_tensor::kMulF, mlir::sparse_tensor::kMulI, mlir::sparse_tensor::kOrI, mlir::sparse_tensor::kSubF, mlir::sparse_tensor::kSubI, and mlir::sparse_tensor::kXorI.
Referenced by genInvariants().
getReductionName()
static StringRef getReductionName (Reduction kind) static
Maps reduction kind to name encoding.
Definition at line 303 of file Sparsification.cpp.
Referenced by genReductionEnd().
isAdmissableTensorExp()
static bool isAdmissableTensorExp (Merger & merger, linalg::GenericOp op, unsigned exp) static
Returns true when the tensor expression is admissable for codegen.
Since all sparse input tensors are admissable, we just need to check whether the output tensor in the tensor expression codegen is admissable.
Definition at line 268 of file Sparsification.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::Merger::isConjunction(), mlir::sparse_tensor::Merger::isDim(), and mlir::sparse_tensor::kSparse.
Referenced by genResult().
isInvariantAffine()
static bool isInvariantAffine (const CodeGen & codegen, AffineExpr a, unsigned ldx, bool & atLevel) static
Determines if affine expression is invariant.
Definition at line 797 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::DimId, mlir::AffineExpr::getKind(), and mlir::Mul.
Referenced by genInvariants().
isParallelFor()
static bool isParallelFor (CodeGen & codegen, bool isOuter, bool isReduction, bool isSparse, bool isVector) static
Returns parallelization strategy.
Any implicit loop in the Linalg operation that is marked "parallel" is a candidate. Whether it is actually converted to a parallel operation depends on the requested strategy.
Definition at line 915 of file Sparsification.cpp.
References mlir::kAnyStorageAnyLoop, mlir::kAnyStorageOuterLoop, mlir::kDenseAnyLoop, mlir::kDenseOuterLoop, and mlir::kNone.
Referenced by genFor().
isVectorFor()
static bool isVectorFor (CodeGen & codegen, bool isInner, bool isSparse) static
Returns vectorization strategy.
Any implicit inner loop in the Linalg operation is a candidate. Whether it is actually converted to SIMD code depends on the requested strategy.
Definition at line 900 of file Sparsification.cpp.
References mlir::kAnyStorageInnerLoop, mlir::kDenseInnerLoop, and mlir::kNone.
Referenced by genFor().
perm()
static unsigned perm (const SparseTensorEncodingAttr & enc, unsigned d) static
Helper method to apply dimension ordering permutation.
Definition at line 91 of file Sparsification.cpp.
Referenced by calculateImplicitMap(), computeIterationGraph(), findSparseAnnotations(), genBuffers(), genInvariants(), genResult(), genSubscript(), getOpToConvert(), makePermutationMap(), and mlir::ContractionOpToDotLowering::matchAndRewrite().
toDim()
static Dim toDim (const SparseTensorEncodingAttr & enc, unsigned d) static
Helper method to translate dim level type to internal representation.
Definition at line 103 of file Sparsification.cpp.
References mlir::sparse_tensor::kDense, mlir::sparse_tensor::kSingle, and mlir::sparse_tensor::kSparse.
Referenced by findSparseAnnotations().
topSortDFS()
static bool topSortDFS (unsigned i, std::vector< unsigned > & visit, std::vector< unsigned > & topSort, std::vector< std::vector< bool >> & adjM) static
A DFS helper to compute a topological sort.
Note that recursion is bounded by the number of implicit loops, which is always small. Returns false when a cycle is detected.
Definition at line 169 of file Sparsification.cpp.
Referenced by computeIterationGraph().
vectorType() [1/2]
static VectorType vectorType (CodeGen & codegen, Type etp) static
Constructs vector type.
Definition at line 500 of file Sparsification.cpp.
Referenced by broadcast(), buildVectorRead(), buildVectorWrite(), castDataPtr(), mlir::spirv::SPIRVType::classof(), mlir::spirv::CompositeType::classof(), mlir::spirv::Deserializer::collect(), mlir::quant::ExpressedToQuantizedConverter::convert(), mlir::VulkanLayoutUtils::decorateType(), elementType(), extractOne(), foldTransferInBoundsAttribute(), genLoad(), genReductionStart(), genVectorInvariantValue(), genVectorLoad(), genVectorMask(), getBitWidth(), getEnclosingforOps(), getI1SameShape(), getMemRefEltSizeInBytes(), mlir::spirv::CompositeType::getNumElements(), mlir::ShapedType::getShape(), mlir::spirv::CompositeType::getSizeInBytes(), mlir::LLVMTypeConverter::getUnrankedMemRefDescriptorSize(), insertOne(), mlir::spirv::MatrixType::isValidColumnType(), isValidQuantizationSpec(), optionallyBroadcast(), parseCallOp(), parseExtractOp(), parseInsertElementOp(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), vectorizeAffineLoad(), vectorizeAsLinalgGeneric(), vectorType(), vectorWidth(), verify(), verifyCastOp(), verifyTransferOp(), and wrapExternalFunction().
vectorType() [2/2]
static VectorType vectorType (CodeGen & codegen, Value ptr) static
Constructs vector type from pointer.
Definition at line 505 of file Sparsification.cpp.
References mlir::Type::cast(), getElementType(), mlir::Value::getType(), and vectorType().