MLIR: lib/Conversion/StandardToSPIRV/StandardToSPIRV.cpp File Reference
StandardToSPIRV.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/Debug.h"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "std-to-spirv-pattern"
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
Functions
static bool isBoolScalarOrVector (Type type)
Returns true if the given type is a boolean scalar or vector type.
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder)
Converts the given srcAttr into a boolean attribute if it holds an integral value.
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder &builder)
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
void mlir::populateStandardToSPIRVPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns)
Appends to a pattern list additional patterns for translating standard ops to SPIR-V ops.
void mlir::populateTensorToSPIRVPatterns (SPIRVTypeConverter &typeConverter, int64_t byteCountThreshold, RewritePatternSet &patterns)
Appends to a pattern list additional patterns for translating tensor ops to SPIR-V ops.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "std-to-spirv-pattern"
Definition at line 24 of file StandardToSPIRV.cpp.
DISPATCH [1/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpFOp, cmpFOp.getResult().getType(), \
                                         adaptor.lhs(), adaptor.rhs());        \
    return success();
Referenced by emulateSignedRemainder().
DISPATCH [2/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpIOp, cmpIOp.getResult().getType(), \
                                         adaptor.lhs(), adaptor.rhs());        \
    return success();
DISPATCH [3/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    if (spirvOp::template hasTrait<OpTrait::spirv::UnsignedOp>() &&            \
        operandType != this->getTypeConverter()->convertType(operandType)) {   \
      return cmpIOp.emitError(                                                 \
          "bitwidth emulation is not implemented yet on unsigned op");         \
    }                                                                          \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpIOp, cmpIOp.getResult().getType(), \
                                         adaptor.lhs(), adaptor.rhs());        \
    return success();
Function Documentation
convertBoolAttr()
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder) static
Converts the given srcAttr into a boolean attribute if it holds an integral value.
Returns null attribute if conversion fails.
Definition at line 43 of file StandardToSPIRV.cpp.
References mlir::Attribute::dyn_cast(), and mlir::Builder::getBoolAttr().
Referenced by emulateSignedRemainder().
convertFloatAttr()
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if dstType is not 32-bit or conversion fails.
Definition at line 80 of file StandardToSPIRV.cpp.
References mlir::Builder::getF32FloatAttr(), and mlir::Type::isF32().
Referenced by emulateSignedRemainder().
convertIntegerAttr()
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if conversion fails.
Definition at line 53 of file StandardToSPIRV.cpp.
References mlir::Builder::getIntegerAttr().
Referenced by emulateSignedRemainder().
emulateSignedRemainder()
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder & builder) static
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
Note that this is needed for Vulkan. Per the Vulkan's SPIR-V environment spec, "for the OpSRem and OpSMod instructions, if either operand is negative the result is undefined." So we cannot directly use spv.SRem/spv.SMod if either operand can be negative. Emulate it via spv.UMod.
Definition at line 108 of file StandardToSPIRV.cpp.
References mlir::Type::cast(), convertBoolAttr(), convertFloatAttr(), convertIntegerAttr(), mlir::OpBuilder::create(), DISPATCH, mlir::failure(), mlir::DenseElementsAttr::get(), mlir::spirv::PointerType::get(), mlir::ShapedType::getDimSize(), getElementType(), mlir::ShapedType::getElementTypeBitWidth(), mlir::ShapedType::getNumElements(), mlir::Operation::getOperands(), mlir::ShapedType::getRank(), mlir::Value::getType(), mlir::ShapedType::hasStaticShape(), mlir::Type::isa(), isBoolScalarOrVector(), mlir::Type::isInteger(), mlir::Type::isIntOrIndexOrFloat(), mlir::spirv::CompositeType::isValid(), mlir::spirv::linearizeIndex(), loc, mlir::ConversionPatternRewriter::notifyMatchFailure(), op, mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, and mlir::success().
isBoolScalarOrVector()
static bool isBoolScalarOrVector (Type type) static
Returns true if the given type is a boolean scalar or vector type.
Definition at line 33 of file StandardToSPIRV.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isInteger().
Referenced by emulateSignedRemainder().