MLIR: lib/Dialect/Traits.cpp File Reference
Traits.cpp File Reference
#include "mlir/Dialect/Traits.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static ArrayRef< int64_t > getShape (Type type)
Returns the shape of the given type.
template<typename iterator_range >
static std::tuple< bool, bool > hasTensorOrVectorType (iterator_range types)
Returns a tuple corresponding to whether range has tensor or vector type.
static bool isCompatibleInferredReturnShape (ArrayRef< int64_t > inferred, ArrayRef< int64_t > existing)
static std::string getShapeString (ArrayRef< int64_t > shape)
Function Documentation
getShape()
static ArrayRef<int64_t> getShape (Type type) static
Returns the shape of the given type.
Scalars will be considered as having a shape with zero dimensions.
Definition at line 117 of file Traits.cpp.
References mlir::Type::dyn_cast().
Referenced by mlir::ShapedType::clone(), createOrFoldDimOp(), mlir::OpTrait::util::getBroadcastedType(), mlir::ShapeAdaptor::getDims(), mlir::ShapedType::getDimSize(), mlir::ShapedType::getDynamicDimIndex(), mlir::ShapedType::getNumDynamicDims(), mlir::ShapedType::getNumElements(), mlir::spirv::MatrixType::getNumRows(), mlir::ShapedType::getRank(), mlir::ShapedType::getShape(), mlir::ValueShapeRange::getShape(), mlir::ValueShapeRange::getValues(), mlir::ShapedType::hasStaticShape(), mlir::ShapedType::isDynamicDim(), BubbleDownBitCastForStridedSliceExtract::matchAndRewrite(), mlir::gpu::MMAMatrixStorageType::operator==(), parseElementAttrHexValues(), reshapeLowerToHigher(), mlir::spirv::MatrixType::verify(), verify(), and mlir::OpTrait::impl::verifyCompatibleOperandBroadcast().
getShapeString()
static std::string getShapeString (ArrayRef< int64_t > shape) static
Definition at line 212 of file Traits.cpp.
References mlir::ShapedType::isDynamic().
Referenced by mlir::OpTrait::impl::verifyCompatibleOperandBroadcast().
hasTensorOrVectorType()
template<typename iterator_range > static std::tuple<bool, bool> hasTensorOrVectorType (iterator_range types) static
Returns a tuple corresponding to whether range has tensor or vector type.
Definition at line 189 of file Traits.cpp.
References mlir::Type::isa().
Referenced by mlir::OpTrait::impl::verifyCompatibleOperandBroadcast().
isCompatibleInferredReturnShape()
static bool isCompatibleInferredReturnShape (ArrayRef< int64_t > inferred, ArrayRef< int64_t > existing) static
Definition at line 195 of file Traits.cpp.
Referenced by mlir::OpTrait::impl::verifyCompatibleOperandBroadcast().